### ISSUE TITLE
Idle detection broken on GNOME

### ISSUE THREAD

**Issue by salim-b** [unobserved-io/Furtherance#154]
In the revamped Furtherance based on Iced (v24.10.2), the idle detection is broken on GNOME. I tested with [Bluefin](https://docs.projectbluefin.io/) ([`bluefin-dx:gts`](https://github.com/ublue-os/bluefin/pkgs/container/bluefin-dx/285415329?tag=gts) which is currently on GNOME 45.6) and Ubuntu 22.04 (GNOME 42.9), using the [Flatpak](https://flathub.org/apps/io.unobserved.furtherance).

When Furtherance is in the foreground while the idle time is exceeded, it crashes:

```
❯ RUST_BACKTRACE=full /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=furtherance io.unobserved.furtherance
thread 'main' panicked at src/app.rs:4594:10:
called `Result::unwrap()` on an `Err` value: Error { kind: Zbus(MethodError(OwnedErrorName("org.freedesktop.DBus.Error.ServiceUnknown"), Some("org.freedesktop.DBus.Error.ServiceUnknown"), Msg { type: Error, serial: 4294967295, reply-serial: 292, body: Signature("s"), fds: [] })) }
stack backtrace:
   0:     0x56139767b8ca - <unknown>
   1:     0x561396e0fbab - <unknown>
   2:     0x561397644672 - <unknown>
   3:     0x5613976803c7 - <unknown>
   4:     0x56139768161c - <unknown>
   5:     0x561397680e65 - <unknown>
   6:     0x561397680dc9 - <unknown>
   7:     0x561397680db4 - <unknown>
   8:     0x561396ca6ff2 - <unknown>
   9:     0x561396ca74f5 - <unknown>
  10:     0x561396f460e4 - <unknown>
  11:     0x561396f36ca3 - <unknown>
  12:     0x561396d10bec - <unknown>
  13:     0x561396d2142e - <unknown>
  14:     0x561396fc370e - <unknown>
  15:     0x561396d48f9a - <unknown>
  16:     0x561396d1debb - <unknown>
  17:     0x561396eeb745 - <unknown>
  18:     0x561396f12533 - <unknown>
  19:     0x561396eea9c5 - <unknown>
  20:     0x7f894e8ef188 - <unknown>
  21:     0x7f894e8ef24b - __libc_start_main
  22:     0x561396d09c75 - <unknown>
  23:                0x0 - <unknown>
```

When Furtherance is not in the foreground, it doesn't crash. But the timer is not paused when the idle time is reached.

**Comment by rickykresslein** [comment]
Thanks for reporting all of these bugs! This is a big one. I'll get to work on it right away.

**Comment by rickykresslein** [comment]
I've tracked this down to an issue with the D-Bus connection when Furtherance is installed via Flatpak. For now, you can fix this by installing Flatseal and changing Furtherance's permissions to allow `D-Bus session bus`.

I'm working on a permanent fix now.

**Comment by rickykresslein** [comment]
The bug was due to a missing permission in the Flatpak manifest (`--talk-name=org.freedesktop.Notifications`), and it crashed the app due to the unsafe unwrap of the Notification. Both of these issues are now fixed. I will release a Flatpak update soon.

**Comment by salim-b** [comment]
Thank you for the quick response and fix! I can confirm that allowing to talk to `org.freedesktop.Notifications` makes the Flatpak work as supposed:

```sh
flatpak override --user --talk-name=org.freedesktop.Notifications io.unobserved.furtherance
```

**Comment by salim-b** [comment]
> When Furtherance is not in the foreground, it doesn't crash. But the timer is not paused when the idle time is reached.

This is still an issue in v24.10.3, thus I openend https://github.com/unobserved-io/Furtherance/issues/155.
